[workspace]

members = [
    "autocompletion-engine",
]

exclude = []

[profile.release]
# Set this to true if you need to debug release builds
debug = false
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[profile.bench]
debug = true
