/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class AutocompletionEngine {
  constructor()
  getAllCompletionsAsString(files: Array<string>): string
  invalidateCache(): void
}
