[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
# Set this to true if you need to debug release builds
debug = false
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# From NAPI-rs
lto = true

[profile.bench]
debug = true
