export CARGO_FLAGS := env_var_or_default("CARGO_FLAGS", "--dev")
export OUT_DIR := env_var_or_default("OUT_DIR", "dist")

build:
	CARGO_FLAGS="{{CARGO_FLAGS}}" pnpm build && (mkdir "{{OUT_DIR}}" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "{{OUT_DIR}}"

build-debug:
	pnpm build:debug && (mkdir "{{OUT_DIR}}" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "{{OUT_DIR}}"

watch:
	pnpm watch

test: build
	CARGO_FLAGS="{{CARGO_FLAGS}}" cargo test
	pnpm test

test-watch: build
	pnpm test:watch

lint:
	cargo clippy --all-features --all-targets -- -D warnings

fmt:
	cargo fmt
	pnpm fmt

clean:
	cargo clean
	rm -rf dist

artifacts:
	pnpm artifacts

universal:
	pnpm universal

version:
	pnpm version
