export CARGO_FLAGS := env_var_or_default("CARGO_FLAGS", "--dev")
export OUT_DIR := env_var_or_default("OUT_DIR", "")

build:
  # /usr/bin/env bash
  set -eu
  pnpm build
  test -z "$OUT_DIR" || ((mkdir "$OUT_DIR" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "$OUT_DIR")

build-debug:
  # /usr/bin/env bash
  set -eu
  pnpm build:debug
  test -z "$OUT_DIR" || ((mkdir "$OUT_DIR" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "$OUT_DIR")

watch:
	pnpm watch

test: test-rust test-napi

test-rust:
	cargo test

test-napi:
	pnpm test

test-watch:
	# CARGO_FLAGS="{{CARGO_FLAGS}}" cargo watch test
	pnpm test:watch

lint:
	cargo clippy --all-features --all-targets -- -D warnings

fmt:
	cargo fmt
	pnpm fmt

clean:
	cargo clean
	rm -rf dist index.js index.d.ts

artifacts:
	pnpm artifacts

universal:
	pnpm universal

version:
	pnpm version
