export CARGO_FLAGS := env_var_or_default("CARGO_FLAGS", "--dev")
export OUT_DIR := env_var_or_default("OUT_DIR", "dist")

build:
	CARGO_FLAGS="{{CARGO_FLAGS}}" yarn build && (mkdir "{{OUT_DIR}}" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "{{OUT_DIR}}"

build-debug:
	yarn build:debug && (mkdir "{{OUT_DIR}}" 2>&- >/dev/null || true) && mv index.js index.d.ts *.node "{{OUT_DIR}}"

watch:
	yarn watch

test: test-rust test-napi

test-rust:
	CARGO_FLAGS="{{CARGO_FLAGS}}" cargo test

test-napi:
	# Need a full JS build for NAPI bindings.
	CARGO_FLAGS="{{CARGO_FLAGS}}" just build-debug
	yarn test

test-watch:
	# CARGO_FLAGS="{{CARGO_FLAGS}}" cargo watch test
	yarn test:watch

lint:
	cargo clippy --all-features --all-targets -- -D warnings

fmt:
	cargo fmt
	yarn fmt

clean:
	cargo clean
	rm -rf dist

artifacts:
	yarn artifacts

universal:
	yarn universal

version:
	yarn version
